version: '3'
services:
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: '${TYPEORM_USERNAME}'
      POSTGRES_PASSWORD: '${TYPEORM_PASSWORD}'
      POSTGRES_DB: '${TYPEORM_DATABASE}'
    ports:
      - '5434:5432'
  redis:
    image: 'redis:alpine'
    container_name: redis
    ports:
      - '6380:6379'
  microservice:
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
