version: '3'
services:
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: '${TYPEORM_USERNAME}'
      POSTGRES_PASSWORD: '${TYPEORM_PASSWORD}'
      POSTGRES_DB: '${TYPEORM_DATABASE}'
    ports:
      - '5434:5432'
    volumes:
      - ./pg-init-scripts/:/docker-entrypoint-initdb.d/
      - pg-data:/var/lib/postgresql/data
  redis:
    image: 'redis:alpine'
    container_name: redis
    ports:
      - '6380:6379'
  siapce-api:
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
  siapce-web:
    build:
      context: ../SIPCE-WEB
    depends_on:
      - siapce-api
    ports:
      - '80:80'

volumes:
  pg-data:
